language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
addons:
  apt:
    packages:
      - sshpass
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && .
  - mkdir build
  - mv * build
  - tar -czf package.tgz build
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH