language: node_js
node_js:
  - "node"
notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/405756795957673984/vuiVjgPEtAfycYHrC6aGj_kOrTe1ndCpH61tBnH5SDizNgCy--8U-vLpH1b5QbFWolIe/travisci
    on_success: always # default: always
    on_failure: always # default: always
    on_start: never   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
cache:
  directories:
    - "node_modules"
addons:
  apt:
    packages:
      - sshpass
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mkdir build
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mv * build
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && tar -czf package.tgz build
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && export SSHPASS=$DEPLOY_PASS
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sshpass -e scp -o StrictHostKeyChecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sshpass -e ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh